version: "3"
services:
  hugo:
    build: .
    command: server -w --bind "0.0.0.0" --baseURL "http://localhost:1313"
    volumes:
      - ./hugo:/var/hugo
    ports:
      - "1313:1313"
    working_dir: /var/hugo
