version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "33:49:f9:39:b3:4b:e8:8e:ed:29:74:4c:6f:46:c8:78"
      - restore_cache:
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install node dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Deploy to gh-page branch
      - run: git config --global user.name "CCI"
      - run: git config --global user.email "<>"
      - run: yarn run deploy

orbs:
  hugo: circleci/hugo@0.2

workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          source: hugo/
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
