version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: ls -lah docs

orbs:
  hugo: circleci/hugo@0.2

workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          source: hugo/
          destination: docs/
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
